inventorymanager/config/routes.rb
Rails.application.routes.draw do
  root 'default#index'
  
  get 'default/index'

  get 'default/about'

  resources :items
  devise_for :employees
  devise_for :admins
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

inventorymanager/app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

inventorymanager/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

inventorymanager/app/models/employee.rb
class Employee < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

inventorymanager/app/models/item.rb
class Item < ApplicationRecord
    
    mount_uploaders :images, ImageUploader
    serialize :images, JSON
    
    enum quality: ["New", "Like New", "Very Good", "Acceptable", "Poor"]
    enum category: ["Furniture", "Electronics", "Appliances", "Clothes", "Other"]
    
    validates :name, presence: true
    validates :description, presence: true
    validates :location, presence: true
    validates :price, presence: true
    validates :images, presence: true
end

inventorymanager/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
  
end

inventorymanager/app/controllers/default_controller.rb
class DefaultController < ApplicationController
  def index
  end

  def about
  end
end

inventorymanager/app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :check_user, except: [:index, :show]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
    
    @qualities = Item.qualities.keys.to_a
    @categories = Item.categories.keys.to_a
  end

  # GET /items/1
  # GET /items/1.json
  def show
    render(:partial => 'item', :object => @item) if request.xhr?
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end
    
    def check_user
      if current_admin
        authenticate_admin!
      elsif current_employee
        authenticate_employee!
      else
        authenticate_employee!
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.fetch(:item, {}).permit(:name, :description, :quality, :quality_desc, :price, :location, :category, { images: [] })
    end
end

inventorymanager/app/helpers/application_helper.rb
module ApplicationHelper
end

inventorymanager/app/helpers/default_helper.rb
module DefaultHelper
end

inventorymanager/app/helpers/items_helper.rb
module ItemsHelper
end

inventorymanager/app/views/admins/shared/_links.html.haml
- if controller_name != 'sessions'
  = link_to "Log in", new_session_path(resource_name)
  %br/
- if devise_mapping.registerable? && controller_name != 'registrations' && resource_name != 'admin'
  = link_to "Sign up", new_registration_path(resource_name)
  %br/
- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to "Forgot your password?", new_password_path(resource_name)
  %br/
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  %br/
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  %br/
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider)
    %br/

inventorymanager/app/views/default/about.html.haml
%h2 About/Contact
%br/
%body
  %p
    Flea Palace and Thrift Store 
    %br/
    (Formally old Sadler School)
    %br/
    6830 bus. 29 N. Reidsville NC 27320
    %br/
    %br/
    Store Hours: 
    %br/ 
    Thu-Fri, 9am to 2pm
    %br/
    Sat, 8am to 5pm
  %p
    Phone: 336.432.2118
    %br/
    Email: elvismover@yahoo.com
%br/
    

inventorymanager/app/views/default/index.html.haml
%p#notice= notice
%h2 Inventory Application!
%br/
%div
  %p
  Welcome to our inventory application. This application is used to store items with a maximum of 
  %br/
  1000 items. Navigate the website via the navigation bar at the top of all pages. The inventory page is the
  %br/
  main page which will list all of our items and if any items are of interest navigate to the about/contact
  %br/
  page to reach out to us.

%br/
//= link_to("Items", "/items")

inventorymanager/app/views/employees/shared/_links.html.haml
- if controller_name != 'sessions'
  = link_to "Log in", new_session_path(resource_name)
  %br/
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Sign up", new_registration_path(resource_name)
  %br/
- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to "Forgot your password?", new_password_path(resource_name)
  %br/
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  %br/
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  %br/
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider)
    %br/

inventorymanager/app/views/items/_form.html.haml
= form_for(item) do |f|
  - if item.errors.any?
    #error_explanation
      %h2
        = pluralize(item.errors.count, "error")
        prohibited this item from being saved:
      %ul
        - item.errors.full_messages.each do |message|
          %li= message
  = f.label :name
  %br/
  .field
    = f.text_field(:name)
    %br/
  = f.label :description
  %br/
  .field
    = f.text_area(:description, size: "40x5")
    %br/
  = f.label :quality
  %br/
  .field
    = f.select(:quality, Item.qualities.keys.to_a)
    %br/
  = f.label :quality_desc
  %br/
  .field
    = f.text_area(:quality_desc)
    %br/
  = f.label :price
  %br/
  .field
    = f.number_field(:price)
    %br/
  = f.label :location
  %br/
  .field
    = f.text_field(:location)
    %br/
  = f.label :category
  %br/
  .field
    = f.select(:category, Item.categories.keys.to_a)
    %br/
  .field
    = f.file_field(:images, multiple: true)
    = f.hidden_field(:images_cache)
    %br/
  .actions
    = f.submit

inventorymanager/app/views/items/_item.html.haml
%h1 Items
%h2
  = item.name
  , #{item.category}
%br/
- item.images.each do |image|
  = image_tag(image.small.url)
%br
Price: $#{item.price}
%br/
Description: #{item.description}
%br/
Quality: #{item.quality},
\#{item.quality_desc}
%br/
Location: #{item.location}
%br/
%br/
%br/
= link_to 'Edit', edit_item_path(@item)
= link_to 'Close', '', id: 'closeLink'

inventorymanager/app/views/items/edit.html.haml
%h1 Editing Item
= render 'form', item: @item
= link_to 'Show', @item
|
= link_to 'Back', items_path

inventorymanager/app/views/items/index.html.haml
Search:&nbsp
%input#ksInput{:onkeyup => "keywordSearch()", :placeholder => "Search for items...", :type => "text"}/
&nbsp&nbsp

Quality: &nbsp
%select#qualityInput{:onchange => "qualityFilter()"} 
  %option{:value => "All"} All
  %option{:value => "New"} New
  %option{:value => "Like New"} Like New
  %option{:value => "Very Good"} Very Good
  %option{:value => "Acceptable"} Acceptable
  %option{:value => "Poor"} Poor

Categories: &nbsp
%select#categoryInput{:onchange => "categoryFilter()"}
  %option{:value => "All"} All
  %option{:value => "Furniture"} Furniture
  %option{:value => "Electronics"} Electronics
  %option{:value => "Appliances"} Appliances
  %option{:value => "Clothes"} Clothes
  %option{:value => "Other"} Other
&nbsp&nbsp

Price Sort: &nbsp  
%button#descending{:onclick => "priceSort(this.id)"} High -> Low

&nbsp

%button#ascending{:onclick => "priceSort(this.id)"} Low -> High
%br/

%h2 Current Inventory
%p#notice= notice
= link_to 'New Item', new_item_path
%table#myTable
  %thead
    %tr
      %th Name
      %th Description
      %th Quality
      %th Price
      %th Category
      %th Location
      %th Options
  %tbody
    - @items.each do |item|
      %tr
        %td= item.name
        %td= item.description
        %td
          = item.quality
          %br/
          %br/
          = item.quality_desc
        %td= item.price
        %td= item.category
        %td= item.location
        %td{:colspan => "3"}
          = link_to 'More Information', item, class: "item-show"
          - if current_admin || current_employee
            = link_to 'Edit', edit_item_path(item)
            = link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' }
%br/

inventorymanager/app/views/items/new.html.haml
%h2 New Item
= render 'form', item: @item
= link_to 'Back', items_path

inventorymanager/app/views/items/show.html.haml
%p#notice= notice
- item = Item.find(params[:id])
%h2
  = item.name
  , #{item.category}
%br/
Price: $#{item.price}
%br/
Description: #{item.description}
%br/
Quality: #{item.quality},
\#{item.quality_desc}
%br/
Location: #{item.location}
%br/
%br/
%br/
= link_to 'Edit', edit_item_path(@item)
|
= link_to 'Back', items_path

inventorymanager/app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title InventoryManager
    = csrf_meta_tags
    //= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    //= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag 'application'
    = javascript_include_tag "application.js"
  %body
    %nav.navbar.navbar-default
      .container-fluid
        / Brand and toggle get grouped for better mobile display
        .navbar-header
          %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.navbar-brand{:href => "/default/index"} InventoryApp
        / Collect the nav links, forms, and other content for toggling
        #bs-example-navbar-collapse-1.collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li
              %a{:href => "/items"} 
                Inventory
                %span.sr-only (current)
          %ul.nav.navbar-nav.navbar-right
            - if admin_signed_in?
              %li= link_to current_admin.username, edit_admin_registration_path
              %li= link_to "Logout", destroy_admin_session_path, :method => :delete
            - elsif employee_signed_in?
              %li= link_to current_employee.username, edit_employee_registration_path
              %li= link_to "Logout", destroy_employee_session_path, :method => :delete
            - else
              %li
                %a{:href => "/default/about"} About/Contact
              %li
                %a{:href => "/admins/sign_in"} Admin
              %li
                %a{:href => "/employees/sign_in"} Staff
        / /.navbar-collapse
      / /.container-fluid
    = yield
  %footer
    